name: Build
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: make
        uses: dante-ev/latex-action@master
        with:
          entrypoint: /usr/bin/make
          # parameters are passed to make
          # make doesn't want to cope with "" as parameter, thus we pass "all" at all places
          # see https://github.com/dante-ev/latex-action/blob/master/action.yml for a list of all args passed by GitHub actions
          root_file: all
          working_directory: all
          compiler: all
          args: all
          extra_system_packages: dist
      - name: publish dist-archive
        uses: actions/upload-artifact@v2
        with:
          name: dist-archive
          path: showexpl*.zip
      - name: publish showexpl.sty
        uses: actions/upload-artifact@v2
        with:
          name: showexpl.sty
          path: showexpl.sty
